const typeObj = {
  10:'Account Bind',
  84:'Guard Refund Crosschain Trx',
  82:'Acceptance Create',
  83:'Acceptance Cancel',
  81:'Contract Transfer',
  79:'Contract Invoke',
  77:'Contract Upgrade',
  76:'Contract Register',
  73:'Pay Back',
  61:'Withdraw',
  60:'Deposit',
  65:'Withdraw Result',
  26:'Miner Generate Multi Asset',
  24:'Miner Create',
  5:'Account Create',
  0:'Transfer',
  11:'Account Unbind',
  12:'Account Multisig Create',
  13:'Asset Create',
  28:'Proposal Create',
  27:'Miner Merge Signatures',
  35:'Guard Member Create',
  36:'Guard Member Update',
  38:'Guard Member Resign',
  47:'Sign Multisig Asset',
  62:'Crosschain Withdraw Without Sign',
  63:'Crosschain Withdraw With Sign',
  64:'Crosschain Withdraw Combine Sign',
  66:'Coldhot Transfer',
  67:'Coldhot Transfer Without Sign',
  68:'Coldhot Transfer With Sign',
  69:'Coldhot Transfer Combine Sign',
  70:'Coldhot Transfer Result',
  71:'Coldhot Cancel Transafer Transaction',
  72:'Coldhot Cancel Uncombined Trx',
  74:'Guard Update Multi Account',
  75:'Asset Real Create',
  85:'Publisher Appointed',
  86:'Asset Fee Modification'
};
export default typeObj;
